version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=2880
      - SCREEN_HEIGHT=1800
    links:
      - selenium-hub:hub
    scale: 2

  edge:
    image: selenium/node-edge:4.0.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=2880
      - SCREEN_HEIGHT=1800
    links:
      - selenium-hub:hub
    scale: 2

  firefox:
    image: selenium/node-firefox:4.0.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=2880
      - SCREEN_HEIGHT=1800
    links:
      - selenium-hub:hub
    scale: 2

  opera:
    image: selenium/node-opera:4.0.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=2880
      - SCREEN_HEIGHT=1800
    links:
      - selenium-hub:hub
    scale: 2

  selenium-hub:
    image: selenium/hub:4.0.0
    container_name: selenium-hub
    environment:
      - GRID_MAX_SESSION=50
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"